name: Build And Deploy Angular Documentation EN

permissions:
  contents: write

on:
  push:
    branches:
      - vnext
      - master
    paths-ignore:
      - 'docs/jquery/**'
      - 'docs/xplat/**'
      - 'docs/wpf/**'
      - 'docs/winforms/**'
      - 'docs/aspnet/**'
      - '**/jp/**'
      - '**/kr/**'
      - 'llms-output/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        type: string
        default: 'vnext'

jobs:
  deploy:
    uses: ./.github/workflows/_cd-deploy.yml
    with:
      locale: en
      platform: angular
      target_ref: ${{ github.event.inputs.branch && (startsWith(github.event.inputs.branch, 'refs/') && github.event.inputs.branch || format('refs/heads/{0}', github.event.inputs.branch)) || github.ref }}
    secrets:
      CLASSIC_PAT_GITHUB: ${{ secrets.CLASSIC_PAT_GITHUB }}
