name: Build And Deploy Documentation JP

permissions:
  contents: read

on:
  push:
    branches:
      - vnext
      - master
    paths-ignore:
      - '**/en/**'
      - '**/kr/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        type: string
        default: 'vnext'

jobs:
  deploy:
    uses: ./.github/workflows/_cd-deploy.yml
    with:
      locale: jp
      target_ref: ${{ github.event.inputs.branch && (startsWith(github.event.inputs.branch, 'refs/') && github.event.inputs.branch || format('refs/heads/{0}', github.event.inputs.branch)) || github.ref }}
    secrets:
      CLASSIC_PAT_GITHUB: ${{ secrets.CLASSIC_PAT_GITHUB }}
