name: Build Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - vnext
      - master
# TODO: add proper filters
#    paths-ignore:
#      - '**/jp/**'
#      - '**/kr/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        type: string
        default: 'vnext'

env:
  BUILD_TYPE: ${{ github.ref_name == 'master' && 'staging' || 'staging' }} # master targets production but for testing purposes we only deploy to staging
  TARGET_REF: ${{ github.event.inputs.branch && (startsWith(github.event.inputs.branch, 'refs/') && github.event.inputs.branch || format('refs/heads/{0}', github.event.inputs.branch)) || github.ref }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ['angular', 'react', 'wc', 'blazor']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_REF }}
          clean: true
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Documentation for ${{ matrix.platform }}
        run: npm run build:${{ env.BUILD_TYPE }}:${{ matrix.platform }}:en

      - name: Package build
        run: |
          cd dist/${{ matrix.platform }}
          zip -r ../../${{ env.BUILD_TYPE }}_${{ matrix.platform }}_en.zip .
          cd ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: igniteui-docs-${{ matrix.platform }}-en
          path: ${{ env.BUILD_TYPE }}_${{ matrix.platform }}_en.zip
          retention-days: 1

      - name: Trigger Deploy Workflow in IgniteUI Actions
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.CLASSIC_PAT_GITHUB }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'IgniteUI',
              repo: 'igniteui-actions',
              event_type: 'igniteui-documentation-cd',
              client_payload: {
                calling_branch: "${{ env.TARGET_REF }}",
                environment: "${{ env.BUILD_TYPE }}",
                artifact_name: "igniteui-docs-${{ matrix.platform }}-en",
                base_href: "docs-${{ matrix.platform }}-new",
                platform: "${{ matrix.platform }}",
                repository: "${{ github.repository }}",
                run_id: "${{ github.run_id }}",
                locale: "en"
              }
            });
